name: Inline Script Exampe
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  run-action:
    name: Run action
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: 'npm'
          cache-dependency-path: package-lock.json

      - name: Install dependencies
        run: npm ci

      - id: getVersion
        uses: ./.github/actions/composite-example
        with:
          json_file_path: 'package.json'
      - run: echo app version is ${{ steps.getVersion.outputs.version }}
        shell: bash

      - name: Greet
        uses: actions/github-script@v6
        with:
          script: |
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.payload.pull_request.number,
              body: ` 👋 Hello @${context.actor}! 
                            What a nice code you contributed! 🚀 `
            });
